### ISSUE TITLE
找寻不到抢购按钮

### ISSUE THREAD

**Issue by aYu-live** [xiaojia21190/jd_seckill_cli#12]
没有寻找到按钮---------
开始访问商品页面---------
开始访问商品页面成功---------
正在尝试寻找抢购按钮点击
一直找不到抢购按钮，抢购按钮好像不是#btn-reservation了，麻烦大佬check一下

**Comment by Joel-Ee** [comment]
一样的问题 :)

**Comment by YinAqu** [comment]
推测抢购按钮已经不是dom加载了所以监听domcontentloaded事件完成并不能代表抢购按钮已经加载了

**Comment by toniol** [comment]
> 推测抢购按钮已经不是dom加载了所以监听domcontentloaded事件完成并不能代表抢购按钮已经加载了

预约也是，我换成 `load` 就可以了预约成功了
